### ISSUE TITLE
Fails to filter out by SNR

### ISSUE THREAD

**Issue by texadactyl** [lacker/seticore#3] opened 2022-05-04 14:07 UTC
Voyager 1 hdf5 input.

```/home/obs/seticore/build/seticore  --max_drift=4.0 --snr=10 *h5```

```
dedopplering Voyager1.single_coarse.fine_res.h5 with max_drift=4.00 snr=10.00; output in Voyager1.single_coarse.fine_res.dat
hit: coarse channel = 0, snr = 4.203041, drift rate = -0.373093, index = 723716   <-----------------------------
hit: coarse channel = 0, snr = 30.621248, drift rate = -0.392226, index = 739933
hit: coarse channel = 0, snr = 245.781174, drift rate = -0.373093, index = 747929
hit: coarse channel = 0, snr = 31.229952, drift rate = -0.392226, index = 756037
hit: coarse channel = 0, snr = 4.019571, drift rate = -0.353960, index = 772028   <---------------------------------
```

**Comment by texadactyl** [comment] 2022-05-04 14:11
On the positive side, the candidate hits are VERY close to turboSETI:
```
find_doppler.0  INFO     Top hit found! SNR 30.612333, Drift Rate -0.392226, index 739933
find_doppler.0  INFO     Top hit found! SNR 245.709610, Drift Rate -0.373093, index 747929
find_doppler.0  INFO     Top hit found! SNR 31.220858, Drift Rate -0.392226, index 756037

```

**Comment by lacker** [comment] 2022-05-04 15:41
Fixed in https://github.com/lacker/seticore/commit/a18780f4e6e7cd95d79cde13775eae3b09dc858f

It should generally find the same hits as turboseti - the known differences in algorithm are the SNR normalization, which is a little bit different just because I found it hard to reproduce the exact same estimated-percentile thing that numpy does, and the window deduplication, because turboseti's calculation of the window size seems like a bug and I'd rather fix it in turboseti than port over the buggy logic. If you find cases that don't seem anything close to turboseti then I'd like to know about them.

**Closed as completed by lacker** 2022-05-04 15:41 UTC
